### PR TITLE
chore: setup preview action

### PR DESCRIPTION
**Pull request by chengcyber**
### Basic Checks

Have you run `rush change` for this change?

- [ ] Yes
- [ ] No

If **No**, please run `rush change` before, this is necessary.

If adding a **new feature**, the PR's description includes:

- [ ] Reason for adding this feature
- [ ] How to use
- [ ] A basic example

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

### Summary

Add a CI to create a preview site per CI where website code is changed.

### How to test it

Tested in this PR. This PR triggers a preview deploy and the CI commits the preview URL in the comment.

### CODE REVIEW

**Comment by tiktok-service** [comment]
Website Preview: https://tiktok.github.io/sparo/_preview/pr-76/

**Comment by tiktok-service** [comment]
## 🚀 Deployment Update

The preview of your changes has been successfully deployed! 🎉

### 🌐 Website Preview

https://tiktok.github.io/sparo/_preview/pr-76/

Please review the changes at the above link. If everything looks good, you can proceed with the merge. If you encounter any issues, please address them and push the changes.

Happy coding! 😃

**Comment by tiktok-service** [comment]
## 🚀 Deployment Update

The preview of your changes has been successfully deployed! 🎉

### 🌐 Website Preview

https://tiktok.github.io/sparo/_preview/pr-76/

Please review the changes at the above link. If everything looks good, you can proceed with the merge. If you encounter any issues, please address them and push the changes.

Happy coding! 😃

**Comment by chengcyber** [comment]
Close due to the fact that we don't want to deploy preview page with tiktok.github.io domain.

**Pull request closed without merging**
